skip_tags: false

branches:
  only:
    - freetds-0.95-for-pymssql

services:
- mssql2008r2sp2

version: "{build}"

shallow_clone: true

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C ..\\misc\\run_with_compiler.cmd"
    WIN_ICONV_VER: 0.0.8
    OPENSSL_VER: 1.0.2g

  matrix:
  - WIDTH: 32
    ARCH: x86
    VS_VERSION: "2008"
    TDSVER: "7.0"

  - WIDTH: 64
    ARCH: x86_64
    VS_VERSION: "2008"
    TDSVER: "7.1"

  - WIDTH: 32
    ARCH: x86
    VS_VERSION: "2010"
    TDSVER: "7.2"

  - WIDTH: 64
    ARCH: x86_64
    VS_VERSION: "2010"
    TDSVER: "7.3"

  - WIDTH: 32
    ARCH: x86
    VS_VERSION: "2015"
    TDSVER: "7.2"

  - WIDTH: 64
    ARCH: x86_64
    VS_VERSION: "2015"
    TDSVER: "7.3"

configuration:
  - release

install:
  # OpenSSL
  - appveyor DownloadFile http://www.npcglib.org/~stathis/downloads/openssl-%OPENSSL_VER%-vs%VS_VERSION%.7z || (ping -n 10 127.0.0.1 >"nul:" & appveyor DownloadFile http://www.npcglib.org/~stathis/downloads/openssl-%OPENSSL_VER%-vs%VS_VERSION%.7z)
  - 7z x openssl-%OPENSSL_VER%-vs%VS_VERSION%.7z
  - ren openssl-%OPENSSL_VER%-vs%VS_VERSION% openssl
  # Make sure the OpenSSL import libs are always available where CMake's FindOpenSSL is able to find them
  - ps: if ($env:WIDTH -eq 64) { cd openssl ; ren -path lib -newName lib32 ; ren -path lib64 -newName lib ; cd .. }
  # win-iconv
  - appveyor DownloadFile https://github.com/win-iconv/win-iconv/archive/v%WIN_ICONV_VER%.zip
  - 7z x v%WIN_ICONV_VER%.zip
  - ren win-iconv-%WIN_ICONV_VER% iconv
  - mkdir iconv-build
  - cd iconv-build
  - if exist "C:\\Program Files (x86)\\Windows Kits\\10\\include\\wdf" ren "C:\\Program Files (x86)\\Windows Kits\\10\\include\\wdf" "00wdf"
  - "%WITH_COMPILER% cmake -G \"NMake Makefiles\" -DBUILD_STATIC=on -DBUILD_SHARED=off -DBUILD_EXECUTABLE=off -DBUILD_TEST=on -DCMAKE_BUILD_TYPE=Release ..\\iconv"
  - "%WITH_COMPILER% nmake"
  - win_iconv_test.exe
  - cd ..\iconv
  - mkdir include
  - mkdir lib
  - copy iconv.h include
  - copy ..\iconv-build\iconv.lib lib
  - cd ..

build_script:
  # build FreeTDS
  # Add relevant OpenSSL DLLs dir to PATH envvar
  - ps: |
      if ($env:WIDTH -eq 32) { $env:PATH = $env:APPVEYOR_BUILD_FOLDER + "\openssl\bin;" + $env:PATH }
      else { $env:PATH = $env:APPVEYOR_BUILD_FOLDER + "\openssl\bin64;" + $env:PATH }
  - mkdir build
  - cd build
  - "%WITH_COMPILER% cmake -G \"NMake Makefiles\" -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=openssl .."
  - "%WITH_COMPILER% nmake"
  - set PATH=%PATH%;c:\openssl-win%WIDTH%
  - src\apps\tsql.exe -C
  - cd ..

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test_script:
  - set INSTANCENAME=SQL2008R2SP2
  - "powershell misc\\sql-server-activate-tcp-fixed-port.ps1"
  # Create freetds.conf
  - cd build
  - echo [global]> freetds.conf.local
  - echo port = 1433>> freetds.conf.local
  - echo tds version = %TDSVER%>> freetds.conf.local
  - echo [local]>> freetds.conf.local
  - echo host = 127.0.0.1>> freetds.conf.local
  # Create PWD
  - echo UID=sa> PWD
  - echo PWD=Password12!>> PWD
  - echo SRV=local>> PWD
  - echo DB=tempdb>> PWD
  - set FREETDSCONF=%CD%\freetds.conf.local
  - set TDSDUMP=%CD%\conndump
  - set TDSDUMPCONFIG=%CD%\confdump
  - set TDS_SKIP_SUCCESS=1
  # Add dirs of our just built DLLs to PATH envvar so everything works
  - set PATH=%CD%\src\ctlib;%CD%\src\dblib;%PATH%
  # register ODBC driver
  - "%WINDIR%\\SysWOW64\\regsvr32 /s src\\odbc\\tdsodbc.dll || %WINDIR%\\system32\\regsvr32 /s src\\odbc\\tdsodbc.dll"
  # Build and run tests
  - "%WITH_COMPILER% nmake check"
  - cd ..

after_test:
  - type %CD%\build\confdump
  - type %CD%\build\conndump
  # Create zipball artifact
  - cd build
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "True") { $env:DESTDIR = "freetds-" + $env:APPVEYOR_REPO_TAG_NAME + "-win-" + $env:ARCH + "-vs" + $env:VS_VERSION }
      else { $env:DESTDIR = "freetds-win-" + $env:ARCH + "-vs" + $env:VS_VERSION }
  - mkdir %DESTDIR%
  - mkdir %DESTDIR%\include
  - cp include/tds_sysdep_public.h ./%DESTDIR%/include/
  - cd ..\include
  - cp bkpublic.h cspublic.h cstypes.h ctpublic.h sqldb.h sqlfront.h sybdb.h syberror.h sybfront.h ../build/%DESTDIR%/include/
  - cd ..\build
  - mkdir %DESTDIR%\lib
  - copy src\ctlib\ct.dll %DESTDIR%\lib\
  - copy src\ctlib\ct.lib %DESTDIR%\lib\
  - copy src\ctlib\ct.dll.manifest %DESTDIR%\lib\
  - copy src\dblib\sybdb.dll %DESTDIR%\lib\
  - copy src\dblib\sybdb.lib %DESTDIR%\lib\
  - copy src\dblib\sybdb.dll.manifest %DESTDIR%\lib\
  - copy src\odbc\tdsodbc.dll %DESTDIR%\lib\
  - copy src\odbc\tdsodbc.lib %DESTDIR%\lib\
  - copy src\odbc\tdsodbc.dll.manifest %DESTDIR%\lib\
  - mkdir %DESTDIR%\lib\static
  - copy src\dblib\db-lib.lib %DESTDIR%\lib\static\
  - copy src\ctlib\libct.lib %DESTDIR%\lib\static\
  - copy src\tds\tds.lib %DESTDIR%\lib\static\
  - copy src\replacements\replacements.lib %DESTDIR%\lib\static\
  # for now, ship the static iconv.lib bundled with the FreeTDS ones
  - copy ..\iconv\lib\iconv.lib %DESTDIR%\lib\static\
  - mkdir %DESTDIR%\bin
  - copy src\apps\*.exe %DESTDIR%\bin\
  - copy src\apps\*.manifest %DESTDIR%\bin\
  # START of non-test code specifically related to creation of artifacts published via GitHub
  - mkdir %DESTDIR%\lib-nossl
  - mkdir %DESTDIR%\lib-nossl\static
  # Build FreeTDS again, this time without linking in OpenSSL at all
  - cd ..
  - mkdir build-nossl
  - cd build-nossl
  - "%WITH_COMPILER% cmake -G \"NMake Makefiles\" -DCMAKE_BUILD_TYPE=Release -DWITH_OPENSSL=off .."
  - "%WITH_COMPILER% nmake"
  - src\apps\tsql.exe -C
  - copy src\ctlib\ct.dll ..\build\%DESTDIR%\lib-nossl\
  - copy src\ctlib\ct.lib ..\build\%DESTDIR%\lib-nossl\
  - copy src\ctlib\ct.dll.manifest ..\build\%DESTDIR%\lib-nossl\
  - copy src\dblib\sybdb.dll ..\build\%DESTDIR%\lib-nossl\
  - copy src\dblib\sybdb.lib ..\build\%DESTDIR%\lib-nossl\
  - copy src\dblib\sybdb.dll.manifest ..\build\%DESTDIR%\lib-nossl\
  - copy src\odbc\tdsodbc.dll ..\build\%DESTDIR%\lib-nossl\
  - copy src\odbc\tdsodbc.lib ..\build\%DESTDIR%\lib-nossl\
  - copy src\odbc\tdsodbc.dll.manifest ..\build\%DESTDIR%\lib-nossl\
  - copy src\dblib\db-lib.lib ..\build\%DESTDIR%\lib-nossl\static\
  - copy src\ctlib\libct.lib ..\build\%DESTDIR%\lib-nossl\static\
  - copy src\tds\tds.lib ..\build\%DESTDIR%\lib-nossl\static\
  - copy src\replacements\replacements.lib ..\build\%DESTDIR%\lib-nossl\static\
  # for now, ship the static iconv.lib bundled with the FreeTDS ones
  - copy ..\iconv\lib\iconv.lib ..\build\%DESTDIR%\lib-nossl\static\
  - cd ..\build
  # END of non-test code specifically related to creation of artifacts published via GitHub
  - 7z a ..\%DESTDIR%.zip %DESTDIR%
  - cd ..

artifacts:
  - path: freetds-*.zip
    name: win-binaries

deploy:
  - provider: GitHub
    description: FreeTDS $(APPVEYOR_REPO_TAG_NAME) Windows binaries for pymssql.
    artifact: win-binaries
    draft: true
    auth_token:
      secure: 0HZDIXKuYdXSLlN7+o9OCBPPh+p+GZ0QJVxLsXFeZWkKAzEi4ELUcnmbekKWIYQO
    on:
      appveyor_repo_tag: true
